SUBDIR = gotsys-read-conf gotsys-useradd gotsys-groupadd gotsys-userhome \
	gotsys-rmkeys gotsys-userkeys gotsys-repo-create gotsys-write-conf \
	gotsys-apply-conf gotsys-apply-webconf

.include <bsd.subdir.mk>
