#got_linux_task:
  #  container:
  #  image: gcc:latest
  #before_build_script: .github/ci/before-install.sh
  #build:script: .github/ci/build.sh

got_ubuntu_task:
  container:
    image: ubuntu:latest
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
  test_script: make install && make tests

got_alpine_linux_task:
  container:
    image: alpine:latest
  script:
    - apk add libevent-dev git build-base bsd-compat-headers bison automake make autoconf libbsd-dev util-linux-dev libressl-dev zlib-dev ncurses-dev
    - .github/ci/build.sh

got_alpine_linux_out_of_tree_task:
  container:
    image: alpine:latest
  script:
    - apk add libevent-dev git build-base bsd-compat-headers bison automake make autoconf libbsd-dev util-linux-dev libressl-dev zlib-dev ncurses-dev
    - ./autogen.sh && mkdir build && (cd build && ../configure && make)

got_freebsd_task:
  freebsd_instance:
    image_family: freebsd-14-2
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
  test_script: make install && make tests

got_macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
