.\"
.\" Copyright (c) 2026 Thomas Adam
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOT-PORTABLE 7
.Os
.Sh NAME
.Nm got-portable
.Nd Notes relevant for the -portable version of Game of Trees
.Sh GOTWEBD WITH AN HTTP SERVER
In order to make use of
.Xr gotwebd 8
an HTTP server needs to be configured to send traffic to
.Xr gotwebd 8 .
For the purposes of illustrating this,
.Xr nginx 1
will be used.
.Ss Nginx Configuration
Setting up nginx involves a server configuration similar to the following:
.Bd -literal -offset indent
https {
	server {
		listen *:80;
		root /var/www/htdocs;

		location / {
			index index.html;
		}

		location /gotweb {
			include fastcgi_params;
			fastcgi_pass unix:/tmp/gotwebd.sock;
		}
	}
}
.Ed
.Pp
With this directive, port 80 is used.
There is the location of
.Dq /
which is serving the page
.Dq index.html .
.Pp
The location
.Dq /gotweb
includes the fastcgi parameters (because
.Xr gotwebd 8
is a FastCGI server, this must be included).
Then, the rest of the requests are forwarded to
.Xr gotwebd 8
over the defined unix domain socket.
Note that the path to the socket must match what's defined in
.Xr gotwebd.conf 5
.Ss Gotwebd Configuration
The following example config shows a bare-minimum example of how to ensure
.Xr gotwebd 8
is listening on the appropriate port, and that the relevant parts from
.Xr nginx 8
are also referenced correctly.
This is not meant as a complete tutorial for configuring
.Xr gotwebd 8 .
For that, see:
.Xr gotwebd 8 and
.Xr gotwebd.conf 5 .
.Pp
Note the in-line comments explaining how and why
.Xr gotwebd 8
is being configured in this way.
.Bd -literal -offset indent

# The "www user" line should match the user that's running nginx.
www user "www-data"

# This is the user which gotwebd should run as.
#
# Note that this user must have permission to read the repositories
# set via `repos_path`.
#
# This should be an unprivileged user.
user n6tadam

# This is the unix domain socket gotwebd will create and listen on.
# This must also be set correctly in nginx's configuration.
listen on socket "/tmp/gotwebd.sock"

# Because we told nginx that we wanted to serve up gotwebd traffic via
# `/gotweb`, we should let gotwebd know this is also where traffic is coming
# from.
gotweb_url_root "/gotweb"

# Matches the home directory of the "www user".
#
# Note that it is assumed that under this directory 
chroot "/var/www"

server "localhost" {
	disable authentication
	site_name "Public repos"
	site_owner "Thomas Adam"
	site_link "Thomas' Projects"

	# This is where all the bare repos live.
	repos_path "/home/n6tadam/p/got/root/repos"
}
.Ed
.Pp
Note that with the configuration above,
.Xr gotwebd 8
expects to serve up artefacts relative to the chroot path, which defaults to:
.Dq htdocs/gotwebd .
These files might be packaged already, and might live somewhere under
.Dq /usr/share/got-portable/ .
However, they are packaged in the release tarball, and the
.Dq gotwebd/files/htdocs/gotwebd
directory should be copied to
.Dq htdocs/
relative to the chroot line in gotwebd's configuration file.
.Sh SEE ALSO
.Xr got 1 ,
.Xr gotwebd.conf 5 ,
.Xr gotwebctl 8 ,
.Xr nginx 8
.Sh AUTHORS
.An Thomas Adam Aq Mt thomas@xteddy.org
