.\"
.\" Copyright (c) 2024 Stefan Sperling <stsp@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOTSYSD.CONF 5
.Os
.Sh NAME
.Nm gotsysd.conf
.Nd gotsysd configuration file
.Sh DESCRIPTION
.Nm
is the run-time configuration file for
.Xr gotsysd 8 .
.Pp
The file format is line-based, with one configuration directive per line.
Comments can be put anywhere in the file using a hash mark
.Pq Sq # ,
and extend to the end of the current line.
Arguments names not beginning with a letter, digit or underscore,
as well as reserved words
.Pq such as Ic listen , Ic repository No or Ic user ,
must be quoted.
Arguments containing whitespace should be surrounded by double quotes
.Pq \&" .
.Pp
Macros can be defined that are later expanded in context.
Macro names must start with a letter, digit, or underscore, and may
contain any of those characters, but may not be reserved words.
Macros are not expanded inside quotes.
For example:
.Bd -literal -offset indent
path = "/var/run/gotsysd.sock"
listen on $path
.Ed
.Sh GLOBAL CONFIGURATION
The available global configuration directives are as follows:
.Bl -tag -width Ds
.It Ic gotd Ic user Ar user
The name of the
.Xr gotd 8
user account.
Defauls to
.Dq _gotd .
.Xr gotsysd 8
will switch to this user account as needed.
.It Ic listen on Ar path
Set the path to the unix socket which
.Xr gotsysd 8
should listen on.
If not specified, the path
.Pa /var/run/gotsysd.sock
will be used.
.It Ic permit Ar identity
Permit
.Xr gotsysd 8
unix socket access to users with the username
.Ar identity .
Group names may be matched by prepending a colon
.Pq Sq \&:
to
.Ar identity .
Numeric IDs are also accepted.
.Pp
Multiple
.Ic permit
rules can be specified.
.Pp
If no
.Ic permit
rule is specified, the users root and _gotd are granted access by default.
.It Ic repository Ic directory Ar path
Set the path to the repository directory within which Git repositories
will be created and managed by
.Xr gotsysd 8 .
This repository directory must be owned by and be exclusively accessible to the
.Xr gotd 8
user.
.Pp
If not specified, the path
.Pa /git
will be used.
.It Ic repository Ic deny Ar identity
Deny repository access to users with the username
.Ar identity .
.Pp
Access rules set in
.Nm
apply to all repositories and override conflicting per-repository access
rules specified in
.Xr gotsys.conf 5 .
.Pp
Group names may be matched by prepending a colon
.Pq Sq \&:
to
.Ar identity .
.Pp
The special user
.Ar identity
.Dq *
(an asterisk) can be used to match all users, including the
.Dq anonymous
user.
.Pp
Multiple access rules can be specified, and the last matching rule
determines the action taken.
If no rule matches, the per-repository rules specified in
.Xr gotsys.conf 5
will take effect.
.It Ic repository Ic permit Ar mode Ar identity
Permit repository access to users with the username
.Ar identity .
.Pp
Access rules set in
.Nm
apply to all repositories and override conflicting per-repository access
rules specified in
.Xr gotsys.conf 5 .
.Pp
The
.Ar mode
argument must be set to either
.Ic ro
for read-only access,
or
.Ic rw
for read-write access.
Group names may be matched by prepending a colon
.Pq Sq \&:
to
.Ar identity .
.Pp
The special user
.Ar identity
.Dq anonymous
can be used when public read-only access to repositories over SSH is desired.
The anonymous user has an empty password, cannot use an SSH public key, and
can only be granted read-only access.
.Pp
See
.Xr gotsh 1
for important hints about how to configure
.Xr sshd 8
to prevent abuse of certain SSH features by anonymous users.
.Pp
The special user
.Ar identity
.Dq *
(an asterisk) can be used to match all users, except the
.Dq anonymous
user.
Read-only anonymous access must be enabled explicitly.
.Pp
Multiple access rules can be specified, and the last matching rule
determines the action taken.
If no rule matches, the per-repository rules specified in
.Xr gotsys.conf 5
will take effect.
.It Ic uid range Ar start Ar end
Set the start and end (inclusive) of the range from which
.Xr gotsysd 8
will allocate user and group IDs when creating user accounts specified in
.Xr gotsys.conf 5 .
The
.Ar start
of this range must be greater than 1000 and must be smaller than the
.Ar end .
.Pp
The default range is 5000 to 5999.
.Pp
User accounts created by
.Xr gotsysd 8
will use the
.Xr gotsh 1
shell.
.It Ic user Ar user
Set the
.Ar user
which will run
.Xr gotsysd 8 .
Initially,
.Xr gotsysd 8
requires root privileges.
Afterwards,
.Xr gotsysd 8
partly drops privileges to its own
.Ar user
and to the
.Xr gotd 8
user.
If not specified, the user _gotsysd will be used.
Numeric user IDs are also accepted.
.EL
.Sh WEB SERVER CONFIGURATION
.Xr gotsysd 8
can automatically manage 
.Xr gotwebd 8
by generating a
.Xr gotwebd.conf 5
configuration file based on configuration directives in
.Nm
and in
.Xr gotsys.conf 5 ,
and then starting or restarting
.Xr gotwebd 8
to apply configuration changes.
.Pp
To activate management of
.Xr gotwebd 8
by 
.Xr gotsysd 8 ,
at least one
.Xr gotwebd.conf 5
.Ic server
must be declared by using the
.Ic web server
configuration directive in
.Nm .
.Pp
Additionally, global parameters for
.Xr gotwebd 8
can be set using the
.Ic gotweb
configuration directive in
.Nm .
.Pp
While
.Xr gotwebd.conf 5
will be automatically generated by
.Xr gotsysd 8 ,
the system administrator must manually
configure
.Xr httpd 8
or another web server and make sure that appropriate requests are forwarded to
.Xr gotwebd 8
via FastCGI.
.Pp
Global parameters for
.Xr gotwebd 8 ,
declared inside curly braces of the
.Ic gotweb Brq ...
configuration directive, are as follows:
.Bl -tag -width Ds
.It Ic control socket Pa path
Set the
.Ar path
to the
.Ux Ns -domain
socket for
.Xr gotwebctl 8
commands.
By default the path
.Pa /var/run/gotwebd.sock
will be used.
.It Ic prefork Ar number
Spawn enough processes such that
.Ar number
requests can be handled in parallel.
By default,
.Xr gotwebd 8
will handle up to 3 requests in parallel.
The maximum allowed is 32.
.It Ic chroot Pa path
Set the path to the
.Xr chroot 2
environment of
.Xr httpd 8 .
If not specified, it defaults to
.Pa /var/www ,
the home directory of the www user.
Setting the
.Ar path
to
.Pa /
effectively disables chroot.
.It Ic htdocs Pa path
Set the path to the directory which contains static files linked from
HTML generated by
.Xr gotwebd 8 ,
such as
.Pa gotweb.css .
The specified
.Ar path
will be looked up relative to the
.Ic chroot
directory of
.Xr httpd 8 .
If not specified then
.Pa htdocs/gotwebd
will be used.
.Pp
The global
.Ic htdocs
directive can be overridden by
.Nm .
.Ic web server
directives.
.It Ic disable authentication
Disable authentication, allowing any browser to view any repository not
hidden via
.Ic hide repositories
and
.Ic hide repository
directives in either
.Nm
or
.Xr gotsys.conf 5 .
.Pp
The global
.Ic disable authentication
directive can be overridden by
.Ic web server
directives in
.Nm
or
.Xr gotsys.conf 5 .
.It Ic enable authentication Oo Ic insecure Oc
Enable authentication, requiring browsers to present a login token cookie
before read-only repository access is granted.
Unless the
.Ic insecure
keyword is used, the login token cookie will be marked as
.Dq Secure ,
which causes browsers to only send the cookie when connected to the
web server over a TLS connection.
.Pp
The global
.Ic enable authentication
directive can be overridden by
.Ic web server
directives in
.Nm
or
.Xr gotsys.conf 5 .
However,
.Xr gotsys.conf 5
deliberately lacks the
.Ic insecure
keyword.
.It Ic login hint user Ar name
Sets the user name displayed in login hints which are shown on the error
page if authentication has failed.
.Pp
If not set then no login hint will be displayed and users will somehow
need to learn about using the
.Xr gotsh 1
weblogin command via other means.
.It Ic login hint port Ar number
Sets the SSH port number displayed in login hints which are shown on the error
page if authentication has failed.
.It Ic user Ar name
Set the
.Ar user
which runs
.Xr gotwebd 8 .
Defaults to the user _gotwebd.
.It Ic www user Ar name
Set the
.Ar user
which runs
.Xr httpd 8 .
Defaults to the user www.
.It Ic listen on socket Ar path
Configure a
.Ux Ns -domain
socket for incoming FastCGI connections.
May be specified multiple times to build up a list of listening sockets.
.Pp
While the specified
.Ar path
must be absolute, it should usually point inside the web server's chroot
directory such that the web server can access the socket.
.Pp
If no
.Ic listen
directive is used,
.Xr gotwebd 8
will listen on the
.Ux Ns -domain
socket at
.Pa /var/www/run/gotweb.sock .
.It Ic listen on Ar address Ic port Ar number
Configure an address and port for incoming FastCGI connections.
May be specified multiple times to build up a list of listening sockets.
.Pp
Valid
.Ar address
arguments are hostnames, IPv4 and IPv6 addresses.
The
.Ar port
argument may be number or a service name defined in
.Xr services 5 .
.Pp
If no
.Ic listen
directive is used,
.Xr gotwebd 8
will listen on the
.Ux Ns -domain
socket at
.Pa /var/www/run/gotweb.sock .
.El
.Pp
A
.Xr gotwebd.conf 5
.Ic server
is declared with:
.Pp
.Ic web server Ar hostname
.Pp
The
.Ar hostname
should be the name which web browsers use to reach the host running the
instance of
.Xr httpd 8
which forwards requests to
.Xr gotwebd 8 .
.Pp
Optional parameters for the web server may be given in curly braces:
.Pp
.Ic web server Ar hostname Brq ...
.Pp
The parameters are as follows:
.Bl -tag -width Ds
.It Ic gotweb_url_root Ar path
Sets the URL path under which
.Xr httpd 8
is routing requests to this
.Xr gotwebd 8
server.
Defaults to
.Dq / .
.Pp
The specified
.Ar path
should match the path of the
.Ic location
block in
.Xr httpd.conf 5
which forwards requests to
.Xr gotwebd 8 .
.It Ic htdocs Pa path
Set the path to the directory which contains static files linked from
HTML generated by
.Xr gotwebd 8 ,
such as
.Pa gotweb.css .
The specified
.Ar path
will be looked up relative to the
.Ic chroot
directory of
.Xr httpd 8 .
.It Ic hide repositories Ar on | off
Controls whether repositories are hidden by default.
Hidden repositories cannot be browsed via
.Xr gotwebd 8 .
.Pp
By default,
.Ic hide repositories
is set to
.Ar off
and all repositories found in the
.Nm
.Ic repository directory
will be displayed.
.It Ic disable authentication
Disable authentication, allowing any browser to view any repository not
hidden via the
.Ic hide repositories
and
.Ic hide repository
directives in
.Xr gotsys.conf 5 .
.Pp
The web server's
.Ic disable authentication
directive can be overridden by directives in
.Xr gotsys.conf 5 .
.It Ic enable authentication Oo Ic insecure Oc
Enable authentication, requiring browsers to present a login token cookie
before read-only repository access is granted.
Unless the
.Ic insecure
keyword is used, the login token cookie will be marked as
.Dq Secure ,
which causes browsers to only send the cookie when connected to the
web server over a TLS connection.
.Pp
The web server's
.Ic enable authentication
directive can be overridden by directives in
.Xr gotsys.conf 5 .
However,
.Xr gotsys.conf 5
deliberately lacks the
.Ic insecure
keyword.
.El
.Pp
Additional parameters for web servers can be set in
.Xr gotsys.conf 5 .
.Xr gotsysd 8
will ignore
.Xr gotsys.conf 5
configuration directives which cannot be mapped to a known web server
.Ar hostname
declared in
.Nm .
.Sh EXAMPLES
The following example shows default settings:
.Bd -literal -offset indent
user _gotsysd
gotd user _gotd
listen on "/var/run/gotsysd.sock"
repository directory "/git"
uid range 5000 5999
.Ed
.Pp
Regardless of what
.Xr gotsys.conf 5
says, allow the user account
.Dq backup-user
to read any repository:
.Bd -literal -offset indent
repository permit ro backup-user
.Ed
.Pp
Regardless of what
.Xr gotsys.conf 5
says, make all repositories read-only:
.Bd -literal -offset indent
repository permit ro "*"
.Ed
.Pp
Regardless of what
.Xr gotsys.conf 5
says, make all repositories inaccessible:
.Bd -literal -offset indent
repository deny "*"
.Ed
.Pp
Display repositories in the default
.Pa /git
repository directory on the web with
.Xr gotwebd 8 ,
using default settings:
.Bd -literal -offset indent
web server "gotweb.example.com"
.Ed
.Pp
Make
.Xr gotwebd 8
hide repositories which are not explicitly unhidden in
.Xr gotsys.conf 5 ,
and enable authentication unless overriden in on per-server or per-repository
basis in
.Xr gotsys.conf 5 :
.Pp
.Bd -literal -offset indent
web server "gotweb.example.com" {
	hide repositories on
	enable authentication
}
.Ed
.Pp
Configure
.Xr gotwebd 8
to listen on a TCP socket:
.Bd -literal -offset indent
gotweb {
	listen on 127.0.0.1 port 9000
}
.Ed
.Sh SEE ALSO
.Xr got 1 ,
.Xr gotsh 1 ,
.Xr gotwebd.conf 5 ,
.Xr gotd 8 ,
.Xr gotsysd 8 ,
.Xr gotwebd 8 ,
.Xr httpd 8 ,
.Xr sshd 8 .
