.\"
.\" Copyright (c) 2020 Tracey Emery <tracey@traceyemery.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt GOTWEBD.CONF 5
.Os
.Sh NAME
.Nm gotwebd.conf
.Nd gotwebd configuration file
.Sh DESCRIPTION
.Nm
is the run-time configuration file for
.Xr gotwebd 8 .
.Pp
The file format is line-based, with one configuration directive per line.
Comments can be put anywhere in the file using a hash mark
.Pq Sq # ,
and extend to the end of the current line.
Arguments names not beginning with a letter, digit or underscore,
as well as reserved words
.Pq such as Ic listen , Ic server No or Ic user ,
must be quoted.
Arguments containing whitespace should be surrounded by double quotes
.Pq \&" .
.Pp
Macros can be defined that are later expanded in context.
Macro names must start with a letter, digit, or underscore, and may
contain any of those characters, but may not be reserved words.
Macros are not expanded inside quotes.
For example:
.Bd -literal -offset indent
lan_addr = "192.168.0.1"
listen on $lan_addr port 9090
.Ed
.Sh GLOBAL CONFIGURATION
The available global configuration directives are as follows:
.Bl -tag -width Ds
.It Ic chroot Ar path
Set the path to the
.Xr chroot 2
environment of
.Xr httpd 8 .
If not specified, it defaults to
.Pa /var/www ,
the home directory of the www user.
Setting the
.Ar path
to
.Pa /
effectively disables chroot.
.It Ic htdocs Ar path
Set the path to the directory which contains static files linked from
HTML generated by
.Xr gotwebd 8 ,
such as
.Pa gotweb.css .
The specified
.Ar path
will be looked up relative to the
.Ic chroot
directory of
.Xr httpd 8 .
If not specified then
.Pa htdocs/gotwebd
will be used.
.Pp
Whether these files will be served by
.Xr gotwebd 8
or by
.Xr httpd 8
depends on how request routing is configured in
.Xr httpd 8 .
.Pp
This setting can also be configured on a per-server basis.
.It Ic gotweb_url_root Ar path
Sets the URL path under which
.Xr httpd 8
is routing requests to
.Xr gotwebd 8 .
Defaults to
.Dq / .
.Pp
The specified
.Ar path
should match the path of the
.Ic location
block in
.Xr httpd.conf 5
which forwards requests to
.Xr gotwebd 8
via the FastCGI socket.
If the URL path is not configured correctly then
.Xr gotwebd 8
will not be able to serve static files from the
.Ic htdocs
directory.
Browsers will not be able to load CSS and image files unless these files
are served directly from
.Xr httpd 8 .
.Pp
This setting can also be configured on a per-server basis.
.It Ic repos_url_path Ar path
Sets the URL path under which Git repositories will be displayed by
.Xr gotwebd 8 .
The
.Ar path
specified here is relative to
.Ic gotweb_url_root .
.Pp
Defaults to
.Dq / .
This default should only be changed if a
.Ic website
is configured as the landing page instead of the usual index page shown by
.Xr gotwebd 8 .
Otherwise, changing
.Ic repos_url_path
will result in
.Dq not found
errors when browsers attempt to visit the gotweb root URL path.
.Pp
This setting can also be configured on a per-server basis.
.It Ic disable authentication
Disable authentication, allowing any browser to view any repository
not hidden via the
.Ic hide repositories ,
.Ic hide repository ,
or
.Ic respect_exportok
directives.
Authentication is disabled by default.
.It Ic enable authentication Oo Ic insecure Oc
Enable authentication, requiring browsers to present a login token cookie
before read-only repository access is granted.
Authentication can also be configured on a per-server or per-repository basis.
.Pp
Browsers presenting a valid login token cookie will be mapped to the
user account which obtained the login token over SSH from the
.Cm weblogin
command of
.Xr gotsh 1 .
.Pp
Unauthenticated browsers will be mapped to the user account which runs
.Xr httpd 8 .
This user account can be set with the
.Ic www user
directive.
Attempts to read repositories as this user will be denied unless
authentication is disabled for the repository.
.Pp
Unless the
.Ic insecure
keyword is used, the login token cookie will be marked as
.Dq Secure ,
which causes browsers to only send the cookie when connected to the
web server over a TLS connection.
.It Ic listen on Ar address Ic port Ar number
Configure an address and port for incoming FastCGI connections.
Valid
.Ar address
arguments are hostnames, IPv4 and IPv6 addresses.
The
.Ar port
argument may be number or a service name defined in
.Xr services 5 .
May be specified multiple times to build up a list of listening sockets.
.It Ic listen on socket Ar path
Configure a
.Ux Ns -domain
socket for incoming FastCGI connections.
May be specified multiple times to build up a list of listening sockets.
.Pp
While the specified
.Ar path
must be absolute, it should usually point inside the web server's chroot
directory such that the web server can access the socket.
.It Ic login hint user Ar name
Sets the user name displayed in login hints which are shown on the error
page if authentication has failed.
This can be used to advertise the name of an anonymous user account which
has been given read access to one or more repositories via the
.Ic permit
directive.
.Pp
If not set then no login hint will be displayed and users will somehow
need to learn about using the
.Xr gotsh 1
weblogin command via other means.
.Pp
This setting can also be configured on a per-server basis.
.It Ic login socket Ar path
Set the
.Ar path
to the
.Ux Ns -domain
socket for
.Xr gotsh 1
.Ic weblogin
commands.
By default the path
.Pa /var/run/gotweb-login.sock
will be used.
.It Ic prefork Ar number
Spawn enough processes such that
.Ar number
requests can be handled in parallel.
By default,
.Xr gotwebd 8
will handle up to 3 requests in parallel.
The maximum allowed is 32.
.It Ic user Ar user
Set the
.Ar user
which will run
.Xr gotwebd 8 .
If not specified, the user _gotwebd will be used.
.It Ic www user Ar user
Set the
.Ar user
which runs
.Xr httpd 8 .
Needed to ensure that the web server can access
.Ux Ns -domain
sockets created by
.Xr gotwebd 8 .
If not specified, the user www will be used.
.El
.Pp
If no
.Ic listen
directive is used,
.Xr gotwebd 8
will listen on the
.Ux Ns -domain
socket at
.Pa /var/www/run/gotweb.sock .
.Sh SERVER CONFIGURATION
At least one server context must exist for
.Xr gotwebd 8
to function.
In case no server context is defined in the configuration file, a default
server context will be used which uses default parameters for all
applicable settings.
.Pp
A server context is declared with a unique
.Ar name ,
followed by server-specific configuration directives inside curly braces:
.Pp
.Ic server Ar name Brq ...
.Pp
If more than one server is defined, each
.Ar name
should match the hostname which browsers use to reach the corresponding server.
The first server defined is used if the requested hostname is not
matched by any server block.
.Pp
The available server configuration directives are as follows:
.Bl -tag -width Ds
.It Ic custom_css Ar path
Set the path to a custom Cascading Style Sheet (CSS) to be used.
If this option is not specified then the default style sheet
.Sq gotweb.css
will be used.
.Pp
This path must be valid in the web server's URL space since browsers
will attempt to fetch it.
.It Ic logo Ar path
Set the path to an image file containing a logo to be displayed.
Defaults to
.Sq got.png .
.Pp
This path must be valid in the web server's URL space since browsers
will attempt to fetch it.
.It Ic htdocs Ar path
Set the path to the directory which contains static files linked from
HTML generated by
.Xr gotwebd 8 ,
such as
.Pa gotweb.css .
The specified
.Ar path
will be looked up relative to the
.Ic chroot
directory of
.Xr httpd 8 .
If not specified then the global
.Ic htdocs
configuration setting applies.
.Pp
Whether these files will be served by
.Xr gotwebd 8
or by
.Xr httpd 8
depends on how request routing is configured in
.Xr httpd 8 .
.It Ic gotweb_url_root Ar path
Sets the URL path under which
.Xr httpd 8
is routing requests to this
.Xr gotwebd 8
server.
Defaults to
.Dq / .
.Pp
The specified
.Ar path
should match the path of the
.Ic location
block in
.Xr httpd.conf 5
which forwards requests to
.Xr gotwebd 8
via the FastCGI socket.
If the URL path is not configured correctly then
.Xr gotwebd 8
will not be able to serve static files from the
.Ic htdocs
directory.
Browsers will not be able to load CSS and image files unless these files
are served directly from
.Xr httpd 8 .
.Pp
If not set then the global
.Ic gotweb_url_root
setting will be used.
.It Ic repos_url_path Ar path
Sets the URL path under which Git repositories will be displayed by
.Xr gotwebd 8 .
The
.Ar path
specified here is relative to
.Ic gotweb_url_root .
.Pp
Defaults to
.Dq / .
This default should only be changed if a
.Ic website
is configured as the landing page instead of the usual index page shown by
.Xr gotwebd 8 .
Otherwise, changing
.Ic repos_url_path
will result in
.Dq not found
errors when browsers attempt to visit the gotweb root URL path.
.Pp
If not set then the global
.Ic repos_url_path
setting will be used.
.It Ic disable authentication
Disable authentication for this server, allowing any browser to view any
repository not hidden via the
.Ic hide repositories ,
.Ic hide repository ,
or
.Ic respect_exportok
directives.
Authentication can also configured on a per-repository basis.
.Pp
If not specified, the global configuration context determines
whether authentication is disabled.
.It Ic enable authentication Oo Ic insecure Oc
Enable authentication, requiring browsers to present a login token cookie
before read-only repository access is granted.
Authentication can also configured on a per-repository basis.
.Pp
If not specified, the global configuration context determines
whether authentication is enabled.
.It Ic hide repositories Ar on | off
Controls whether repositories are hidden by default.
Hidden repositories cannot be browsed via
.Xr gotwebd 8 .
.Pp
By default,
.Ic hide repositories
is set to
.Ar off
and all repositories found in the
.Ic repos_path
will be displayed.
.Pp
If
.Ic hide repositories
is set to
.Ar on
then a repository will only be displayed if its repository-specific
.Ic hide repository
parameter is set to
.Ar off .
Repositories will be hidden regardless of whether authentication is
enabled and has failed or succeeded.
.It Ic login hint user Ar name
Sets the user name to use in login hints displayed when authentication fails.
If not set then the login hint setting in the global configuration context
will be used.
.It Ic logo_url Ar url
Set a hyperlink for the logo.
Defaults to
.Lk https://gameoftrees.org .
.It Ic max_commits_display Ar number
Set the maximum amount of commits and tags displayed per page.
Defaults to 25.
.It Ic max_repos_display Ar number
Set the maximum amount of repositories displayed on the index screen.
Defaults to 25.
Set to zero to show all the repositories without pagination.
.It Ic repos_path Ar path
Set the path to the directory which contains Git repositories that
the server should publish.
This path is absolute.
Repositories can be served even if they reside outside the web server's
chroot directory.
.Pp
Defaults to
.Pa /got/public
inside the web server's chroot directory.
The
.Cm chroot
directive must be used before the server declaration in order to
take effect.
.It Ic repository Ar name Brq ...
Set options which apply to a particular repository served by this server.
.Pp
A repository context is declared with a unique
.Ar name ,
followed by repository-specific configuration directives inside curly braces.
.Pp
The repository will be looked up within the server's
.Ar repos_path ,
where the directory
.Ar name
can exist with or without a
.Dq .git
suffix.
.Pp
For each repository, access rules can be configured using the
.Ic permit
and
.Ic deny
configuration directives.
Multiple access rules can be specified, and the last matching rule
determines the action taken.
.Pp
If no access rules are set in a repository context, or if a repository exists
in the server's
.Ar repos_path
without being mentioned in
.Nm
at all, then the access rules set in the server and global configuration
contexts apply.
If no rule matches then the repository will be inaccessible if authentication
is enabled.
.Pp
The available repository configuration directives are as follows:
.Bl -tag -width Ds
.It Ic deny Ar identity
Deny repository access to users with the username
.Ar identity .
Group names may be matched by prepending a colon
.Pq Sq \&:
to
.Ar identity .
Numeric IDs are also accepted.
.It Ic permit Ar identity
Permit repository access to users with the username
.Ar identity .
Group names may be matched by prepending a colon
.Pq Sq \&:
to
.Ar identity .
Numeric IDs are also accepted.
.It Ic disable authentication
Disable authentication, allowing any browser to view the repository.
Any access rules configured with
.Ic permit
or
.Ic deny
directives for this repository will be ignored.
.Pp
If not specified, the server context or global context determines
whether authentication is disabled.
.It Ic enable authentication Oo Ic insecure Oc
Enable authentication, requiring browsers to present a login token cookie
before read-only repository access is granted.
.Pp
If not specified, the server context or global context determines
whether authentication is enabled.
.It Ic hide repository Ar on | off
Controls whether the repository is hidden.
Hidden repositories cannot be browsed via
.Xr gotwebd 8 .
.Pp
If not set, the server context's
.Ic hide repositories
parameter determines whether
.Xr gotwebd 8
will display the repository.
.El
.It Ic website Ar url-path Brq ...
Show a web site when the browser visits the given
.Ar url-path .
The web site's content is composed of files in a Git repository.
.Pp
While the underlying repository is subject to authentication as usual,
web site content is always public, and cannot be hidden via the
.Ic hide repository
or
.Ic respect_exportok
directives.
.Pp
The available
.Ic website
configuration paramters are as follows:
.Pp
.Bl -tag -width Ds
.It Ic repository Ar name
Serve web site content from the specified Git repository.
The repository will be looked up within the server's
.Ar repos_path ,
where the directory
.Ar name
can exist with or without a
.Dq .git
suffix.
.Pp
The
.Ic repository
parameter is mandatory.
.It Ic branch Ar name
Look up files to serve as web site content on the specified branch
in the repository.
By default, the branch resolved via the repository's HEAD reference is used.
.Pp
If the
.Ar name
does not begin with
.Dq refs/heads
then the
.Ar name
is searched in the
.Dq refs/heads
reference namespace.
.It Ic path Ar path
Look up files to serve as web site content at the specified path
in the repository.
Defaults to the root directory, 
.Dq / .
.El
.It Ic respect_exportok Ar on | off
Set whether to display the repository only if it contains the magic
.Pa git-daemon-export-ok
file, regardless of whether authentication is enabled and has failed or
succeeded.
Disabled by default.
.It Ic show_repo_age Ar on | off
Toggle display of last repository modification date.
Enabled by default.
.It Ic show_repo_cloneurl Ar on | off
Toggle display of clone URLs for a repository.
This requires the creation of a
.Pa cloneurl
file inside the repository which contains one URL per line.
Enabled by default.
.It Ic show_repo_description Ar on | off
Toggle display of the repository description.
Enabled by default.
The
.Pa description
file in the repository should be updated with an appropriate description.
.It Ic show_repo_owner Ar on | off
Set whether to display the repository owner.
Enabled by default.
This requires the creation of an
.Pa owner
file in the repository or adding an
.Sq owner
field under the [gotweb] or [gitweb] section in the
.Pa config
file inside the repository.
For example:
.Bd -literal -offset indent
[gotweb]
owner = "Your Name"
.Ed
.Pp
The
.Pa owner
file has priority over the
.Pa config
if present.
.It Ic site_link Ar string
Set the displayed site link name for the index page.
Defaults to
.Sq Repos .
.It Ic site_name Ar string
Set the displayed site name title.
Defaults to
.Sq Gotweb .
.It Ic site_owner Ar string
Set the displayed site owner.
Defaults to
.Sq Got Owner .
.It Ic show_site_owner Ar on | off
Toggle display of the site owner.
Enabled by default.
.It Ic summary_commits_display Ar number
The maximum number of commits to show in the summary page.
Defaults to 10.
.It Ic summary_tags_display Ar number
The maximum number of tags to show in the summary page.
Defaults to 3.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa /etc/gotwebd.conf
Default location of the
.Nm
configuration file.
.It Pa /var/www/run/gotweb.sock
Default location for the
.Xr gotwebd 8
.Ux Ns -domain
socket.
.El
.Sh EXAMPLES
A sample configuration which allows public browsing:
.Bd -literal -offset indent
www user "www"   # www username needs quotes since www is a keyword

server "localhost" {
	site_name	"my public repos"
	site_owner	"Flan Hacker"
	site_link	"Flan' Projects"
}
.Ed
.Pp
Another example, this time listening on a local port instead of the
implicit
.Ux Ns -domain
socket, and serving repositories located outside the web server's chroot:
.Bd -literal -offset indent
listen on 127.0.0.1 port 9000
listen on ::1 port 9000

server "localhost" {
	site_name	"my public repos"
	repos_path	"/var/git"
}
.Ed
.Pp
This example illustrates how
.Xr gotwebd 8
can serve static web sites out of Git repositories:
.Bd -literal -offset indent
# This server displays just one web site, no Git repositories.
server "www.example.com" {
	# Do not display any Git repository data.
	hide repositories on

	# Serve the www.git repository as a web site when
	# the browser visits "www.example.com".
	website "/" {
		repository "www"  # /var/www/got/public/www.git

		# Any child URL paths the browser wants to
		# visit will be looked up in www.git, on
		# the branch which the symbolic HEAD
		# reference points to.
	}
}

# This server displays both web sites and Git repositories.
server "project.example.com" {
	repos_path	"/var/git"

	# Display Git repositories when the URL path "/gotweb/" is
	# is visited by the browser.
	gotweb url_path "/gotweb"

	website "/" {
		# Display the "www" repository as a web site when
		# the browser visits "project.example.com".
		repository "www"  # /var/git/www or /var/git/www.git

		# Any child URL path the browser wants to visit will
		# be looked up in www.git, except for "gotweb/" which
		# maps to repos_path, and "docs/" which is used by
		# other repositories defined below.
	}

	repository "www.git" {	# /var/git/www or /var/git/www.git
		# Otherwise, hide data in this repository. It will
		# not be shown under the "/gotweb" URL path.
		hide repository on
	}

	# Display the src.git repository's "docs/html" directory
	# as found on the main branch as a web site at the
	# URL "project.example.com/docs/".
	website "/docs" {
		repository "src"
		path "/docs/html"
		branch "main"  # same as "refs/heads/main"

		# Any child URL paths the browser wants to visit will
		# be looked up in src.git, except for "gotweb/"
		# which maps to repos_path, and "docs/api/" which is
		# used by another web site defined below.
	}

	repository "src" {	# /var/git/src or /var/git/src.git
		# Otherwise, hide data in this repository. It will
		# not be shown under the "/gotweb" URL path.
		hide repository on
	}

	# Display the "main" branch of api-docs.git repository
	# as a web site at the URL
	# "project.example.com/docs/api/latest/".
	website "/docs/api/latest" {
		repository "api-docs.git"
		branch "main"
	}

	# Display the "1.x-stable" branch of the api-docs.git
	# as a web site at the URL
	# "project.example.com/docs/api/1.x/".
	website "/docs/api/1.x" {
		repository "api-docs.git"
		branch "1.x-stable"
	}

	# The api-docs repository will also be shown under "/gotweb"
	# because the hide repositories and hide repository
	# setings default to "off".
}
.Ed
.Pp
The following example illustrates the use of directives related to
authentication:
.Bd -literal -offset indent
# 3 scopes: global, per-server, per-repository

enable authentication  # override the default which is 'disable'

# Allow user "admin" to read anything unless overridden with a
# "deny" rule later.
permit "admin"

server "public.example.com" {
	disable authentication	# override global setting
	repos_path "/var/www/got/public"
}

server "secure.example.com" {
	permit flan_squee	# grant access to flan_squee
	permit :developers	# grant access to developers group

	repos_path		"/var/git"

	# Tell vistors who see a "login failed" error page that
	# they can log in as the "anonymous" user via ssh.
	login hint user "anonymous"

	repository "got" {  # /var/git/got and /var/git/got.git
		# Grant access to users who have authenticated as
		# the anonymous user to gotsh(1), which anyone with
		# an SSH client sbould be able to do.
		# Dumb web crawlers will remain locked out.
		permit "anonymous"
	}

	repository "public" {
		# As an exception, allow any web browsers and
		# web crawlers to view this repository.
		disable authentication
	}

	repository "secret" {
		deny admin # not even the admin can read this
	}
}
.Ed
.Sh SEE ALSO
.Xr got 1 ,
.Xr httpd.conf 5 ,
.Xr services 5 ,
.Xr gotwebd 8 ,
.Xr httpd 8
